version: '3.8'

# Pega as variáveis de ambiente do arquivo .env.production
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - "80:80"  # Porta padrão para produção
    env_file:
      - .env.production  # Usa o arquivo .env.production
    environment:
      # Variáveis de ambiente principais
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=https://qualidadehd.direcaoclinica.com.br
      
      # Database - usando MariaDB
      - DB_CONNECTION=mariadb
      - DB_HOST=mariadb  # Nome do serviço MariaDB
      - DB_PORT=3306
      - DB_DATABASE=hemodialise_gqa
      - DB_USERNAME=Usr_QltGest@2025
      - DB_PASSWORD=Qlt!H0sp#2025
      
      # Configurações de cache e sessão para produção
      - CACHE_DRIVER=database
      - SESSION_DRIVER=database
      - SESSION_LIFETIME=480
      - SESSION_SECURE_COOKIE=true
      - QUEUE_CONNECTION=database
      
      # JWT
      - JWT_SECRET=${JWT_SECRET:-your-secret-key-change-in-production}
      
      # Flags de inicialização
      - RUN_MIGRATIONS=true
      - RUN_SEEDERS=false
    depends_on:
      mariadb:
        condition: service_healthy
    volumes:
      - app-storage:/var/www/html/storage
      - app-cache:/var/www/html/bootstrap/cache
    networks:
      - hemodialise-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/up"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s  # Reduzido para mais velocidade

  mariadb:
    image: mariadb:10.11
    env_file:
      - .env.production  # Usa o mesmo arquivo .env.production para consistência
    environment:
      - MARIADB_DATABASE=hemodialise_gqa
      - MARIADB_USER=Usr_QltGest@2025
      - MARIADB_PASSWORD=Qlt!H0sp#2025
      - MARIADB_RANDOM_ROOT_PASSWORD=true
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - hemodialise-network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  mariadb-data:
    driver: local
  app-storage:
    driver: local
  app-cache:
    driver: local

networks:
  hemodialise-network:
    driver: bridge
