#!/bin/bash

echo "=========================================="
echo "🚨 PUSH URGENTE NECESSÁRIO"
echo "=========================================="
echo ""
echo "Você tem 3 commits que NÃO estão no GitHub:"
echo ""
git log origin/main..HEAD --oneline
echo ""
echo "=========================================="
echo "O Dokploy está usando código ANTIGO!"
echo "Por isso está tentando copiar .env.docker"
echo "=========================================="
echo ""
echo "SOLUÇÃO:"
echo ""
echo "1️⃣  PUSH PARA GITHUB:"
echo "   git push origin main"
echo ""
echo "   Se pedir senha/usuário:"
echo "   - Usuário: seu-usuario-github"
echo "   - Senha: seu-personal-access-token"
echo ""
echo "2️⃣  REDEPLOY NO DOKPLOY:"
echo "   http://212.85.1.175:3000"
echo "   - Ir no serviço qualidadehd"
echo "   - Clicar em Redeploy"
echo ""
echo "=========================================="
echo "IMPORTANTE: SEM O PUSH, NADA FUNCIONA!"
echo "=========================================="
echo ""

read -p "Pressione ENTER para tentar fazer o push agora..."

git push origin main

if [ $? -eq 0 ]; then
    echo ""
    echo "✅ PUSH CONCLUÍDO COM SUCESSO!"
    echo ""
    echo "Próximo passo:"
    echo "1. Acesse: http://212.85.1.175:3000"
    echo "2. Configure as variáveis de ambiente (veja SETUP-FINAL.md)"
    echo "3. Faça o REDEPLOY"
else
    echo ""
    echo "❌ PUSH FALHOU!"
    echo ""
    echo "Você precisa configurar autenticação:"
    echo ""
    echo "Opção A - Personal Access Token (Recomendado):"
    echo "  1. Acesse: https://github.com/settings/tokens"
    echo "  2. Gere um novo token com permissão 'repo'"
    echo "  3. Execute:"
    echo "     git push https://SEU_TOKEN@github.com/cairo-castro/hemodialise.git main"
    echo ""
    echo "Opção B - SSH:"
    echo "  1. Configure chave SSH no GitHub"
    echo "  2. Execute:"
    echo "     git remote set-url origin git@github.com:cairo-castro/hemodialise.git"
    echo "     git push origin main"
fi
