#!/bin/bash

echo "=============================================="
echo "Push para GitHub - Sistema Hemodiálise"
echo "=============================================="
echo ""
echo "Commits pendentes:"
git log origin/main..HEAD --oneline
echo ""
echo "=============================================="
echo ""
echo "Para fazer o push, execute um dos comandos:"
echo ""
echo "1. Se você tem SSH configurado:"
echo "   git remote set-url origin git@github.com:cairo-castro/hemodialise.git"
echo "   git push origin main"
echo ""
echo "2. Se você vai usar HTTPS (vai pedir credenciais):"
echo "   git push origin main"
echo ""
echo "3. Se você tem um Personal Access Token:"
echo "   git push https://SEU_TOKEN@github.com/cairo-castro/hemodialise.git main"
echo ""
echo "=============================================="
echo ""
echo "Arquivo importante que precisa ser enviado:"
echo "  - .env.docker (configuração do banco de dados)"
echo ""
echo "Depois do push, acesse o Dokploy e faça o redeploy:"
echo "  http://212.85.1.175:3000"
echo ""
