#!/bin/bash

echo "=========================================="
echo "🚀 PUSH FIX: PHP-FPM Socket (Cache Bust)"
echo "=========================================="
echo ""
echo "✅ Commit pronto: 108a858"
echo "   fix: força rebuild Docker para aplicar listen.group PHP-FPM"
echo ""
echo "📦 Mudanças:"
echo "   - Dockerfile.production: cache-busting timestamp"
echo "   - PROBLEMA-SOCKET-PHP-FPM-FINAL.md: documentação completa"
echo ""
echo "🎯 O Que Este Fix Resolve:"
echo "   - Força rebuild SEM CACHE do Docker"
echo "   - Aplica listen.group = nginx no PHP-FPM"
echo "   - Socket será criado com permissões corretas"
echo "   - Nginx conseguirá conectar ao PHP-FPM"
echo "   - 502 Bad Gateway será resolvido!"
echo ""
echo "=========================================="
echo "EXECUTE AGORA:"
echo "=========================================="
echo ""
echo "cd /home/Hemodialise/sistema-hemodialise"
echo "git push"
echo ""
echo "=========================================="
echo "APÓS O PUSH:"
echo "=========================================="
echo ""
echo "1. Acesse: http://212.85.1.175:3000"
echo "2. Projects > qualidade > qualidadehd"
echo "3. ☑️ Marque: 'No Cache' ou 'Clean Build'"
echo "4. Clique: 'Redeploy'"
echo "5. Aguarde: ~10-15 minutos"
echo ""
echo "=========================================="
echo "VALIDAÇÃO:"
echo "=========================================="
echo ""
echo "# Após deploy, verificar:"
echo "CONTAINER=\$(docker ps | grep qualidadehd | awk '{print \$1}')"
echo ""
echo "# 1. Verificar listen.group configurado:"
echo "docker exec \$CONTAINER cat /usr/local/etc/php-fpm.d/www.conf | grep '^listen'"
echo ""
echo "# Deve mostrar:"
echo "# listen = /var/run/php-fpm.sock"
echo "# listen.owner = nginx"
echo "# listen.group = nginx    ← ESTA LINHA!"
echo "# listen.mode = 0660"
echo ""
echo "# 2. Verificar socket existe:"
echo "docker exec \$CONTAINER ls -la /var/run/ | grep php"
echo ""
echo "# Deve mostrar:"
echo "# srw-rw---- 1 nginx nginx 0 php-fpm.sock"
echo ""
echo "# 3. Testar aplicação:"
echo "curl -H 'Host: qualidadehd.direcaoclinica.com.br' http://localhost/"
echo ""
echo "# Deve retornar: HTML do Laravel (página de login)"
echo ""
echo "=========================================="
echo "📖 Documentação: PROBLEMA-SOCKET-PHP-FPM-FINAL.md"
echo "=========================================="
