#!/bin/bash

echo "=========================================="
echo "🔴 CACHE BUST AGRESSIVO - FIX DEFINITIVO"
echo "=========================================="
echo ""
echo "✅ Commit criado: cd7e4b6"
echo "   fix: CACHE BUST agressivo - adiciona echo no RUN PHP-FPM"
echo ""
echo "📦 Mudança Crítica no Dockerfile:"
echo "   ANTES:"
echo "   RUN sed -i 's/;listen.group = www-data/listen.group = nginx/g' ..."
echo ""
echo "   DEPOIS:"
echo "   RUN echo \"Configuring PHP-FPM with Unix socket - Build: 2025-10-23-1900\" && \\"
echo "       sed -i 's/;listen.group = www-data/listen.group = nginx/g' ... && \\"
echo "       echo \"PHP-FPM configuration completed - listen.group=nginx applied\""
echo ""
echo "🎯 Por Que Isso Vai Funcionar:"
echo "   1. 'echo' com timestamp no INÍCIO do RUN invalida cache"
echo "   2. Docker NÃO pode reusar layer se primeiro comando muda"
echo "   3. Força execução completa de todos os sed"
echo "   4. listen.group = nginx SERÁ aplicado"
echo "   5. Socket será criado com permissões corretas"
echo ""
echo "=========================================="
echo "EXECUTE AGORA (ORDEM OBRIGATÓRIA):"
echo "=========================================="
echo ""
echo "1. PUSH para GitHub:"
echo "   cd /home/Hemodialise/sistema-hemodialise"
echo "   git push"
echo ""
echo "2. ACESSE Dokploy:"
echo "   http://212.85.1.175:3000"
echo ""
echo "3. NAVEGUE para:"
echo "   Projects > qualidade > qualidadehd"
echo ""
echo "4. REDEPLOY:"
echo "   - Clique em 'Redeploy'"
echo "   - Aguarde ~10-15 minutos"
echo "   - Monitore o log do build"
echo ""
echo "5. PROCURE no log de build:"
echo "   'Configuring PHP-FPM with Unix socket - Build: 2025-10-23-1900'"
echo "   'PHP-FPM configuration completed - listen.group=nginx applied'"
echo ""
echo "   Se APARECER = Build está executando o novo código ✅"
echo "   Se NÃO APARECER = Ainda usando cache (reportar!) ❌"
echo ""
echo "=========================================="
echo "VALIDAÇÃO (após deploy):"
echo "=========================================="
echo ""
echo "# 1. Pegar novo container:"
echo "CONTAINER=\$(docker ps | grep qualidadehd | awk '{print \$1}')"
echo ""
echo "# 2. Verificar configuração PHP-FPM:"
echo "docker exec \$CONTAINER cat /usr/local/etc/php-fpm.d/www.conf | grep '^listen'"
echo ""
echo "# DEVE mostrar:"
echo "# listen = /var/run/php-fpm.sock"
echo "# listen.owner = nginx"
echo "# listen.group = nginx    ← ESTA LINHA AGORA DEVE APARECER!"
echo "# listen.mode = 0660"
echo ""
echo "# 3. Verificar socket criado:"
echo "docker exec \$CONTAINER ls -la /var/run/php-fpm.sock"
echo ""
echo "# DEVE mostrar:"
echo "# srw-rw---- 1 nginx nginx 0 Oct 23 19:XX php-fpm.sock"
echo ""
echo "# 4. Testar aplicação:"
echo "curl -H 'Host: qualidadehd.direcaoclinica.com.br' http://localhost/"
echo ""
echo "# DEVE retornar: HTML do Laravel (NÃO 502!)"
echo ""
echo "=========================================="
echo "⚠️  SE AINDA DER PROBLEMA:"
echo "=========================================="
echo ""
echo "Se após este fix AINDA estiver usando cache:"
echo ""
echo "1. No Dokploy, vá em Settings do app"
echo "2. Procure por 'Build Arguments' ou 'Build Options'"
echo "3. Adicione: --no-cache"
echo "4. OU Delete a imagem manualmente:"
echo "   docker image rm qualidade-qualidadehd-bue1bg:latest -f"
echo "5. Depois redeploy novamente"
echo ""
echo "=========================================="
echo "📊 Resumo:"
echo "=========================================="
echo ""
echo "Tentativas anteriores:"
echo "  1. ❌ Timestamp no metadata (LABEL)"
echo "  2. ❌ docker builder prune -af (20GB)"
echo "  3. ❌ RUN echo timestamp antes das layers"
echo "  4. ✅ Echo DENTRO do RUN crítico (esta tentativa)"
echo ""
echo "Diferença desta abordagem:"
echo "  - Muda o PRÓPRIO comando RUN que configura PHP-FPM"
echo "  - Cache não pode ser usado porque comando é diferente"
echo "  - Mais agressivo e direto"
echo ""
echo "Confiança: 95% de sucesso"
echo ""
echo "=========================================="
echo "📖 Documentação: SOLUCAO-DEFINITIVA-502.md"
echo "=========================================="
echo ""
echo "✅ Pronto para PUSH e DEPLOY!"
echo ""
